name: cappLogin
main: org.cappmc.sniper722.cappLogin.cappLogin
version: 1.0b
commands:
   capplogin:
      description: Turn on/off/reload the login.
      usage: /<command> <on/off/reload>
      permission: cappLogin.all
      permission-message: You don't have <permission>